spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yogi_JPA?serverTimezone=UTC
    username: test
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: afassakjdhajskdhlaskhdlkahlksahgkalhrskjghdlkshgjlsdahgjhsjknkfnkdsnfkjndsjkfnsjfndjsnfjkdnf
  EXP_TIME: 3600000

